// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/ostrova",
  metaTitle: "Комплекс „Острова“ | Сватби и тържества край реката, Пловдив",
  metaDescription: "Комплекс до Гребния канал в Пловдив: ресторант със 160 места и дансинг, градина и басейн. Запитване за дата на 088 774 2011.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Комплекс „Острова“",
  nameEn: "Complex Ostrova",
  town: "Пловдив",
  since: "",
  phone: "088 774 2011",
  phoneHref: "tel:+359887742011",
  email: "hotelostrova@abv.bg",
  logoSrc: "/brand/ostrova-mark.webp",
  logoInNav: false,
  address: "ул. „Парк култура и отдих“ 40, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Комплекс „Острова“: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "/atmosphere/hero-ostrova.webp",
  wallGarden: "/atmosphere/wall-gradina.webp",
  wallHall: "/atmosphere/wall-masite.webp",
  wallTerrace: "/atmosphere/wall-otgore.webp",
  tableBand: "/atmosphere/band-masata.webp",
  heroTone: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Ресторантът",
        note: "с обособен дансинг",
        value: "160 места",
      },
      {
        space: "Градината и дворът",
        note: "на открито край реката",
        value: "по договаряне",
      },
      {
        space: "Стаите",
        note: "за гостите, които остават",
        value: "на място",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите",
        when: "начало",
      },
      {
        what: "Вечеря в комплекса",
        when: "вечерта",
      },
      {
        what: "Вечерта продължава",
        when: "до късно",
      },
    ],
    packagesNote: "Комплекс „Острова“ не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The restaurant",
        note: "with its own dance floor",
        value: "160 seats",
      },
      {
        space: "The garden and courtyard",
        note: "outdoors by the river",
        value: "on request",
      },
      {
        space: "The rooms",
        note: "for guests who stay",
        value: "on site",
      },
    ],
    timetable: [
      {
        what: "Guests are received",
        when: "start",
      },
      {
        what: "Dinner at the complex",
        when: "evening",
      },
      {
        what: "The evening goes on",
        when: "till late",
      },
    ],
    packagesNote: "Complex Ostrova publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Комплекс за деня, встрани от центъра.",
    heroUnder: "До Гребния канал, край реката в Пловдив.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Снимка на комплекса",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Комплексът, градината и дворът.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "снимките са техни собствени, от ostrova-plovdiv.com",
  },
  en: {
    heroTitle: "A complex for the day, away from the centre.",
    heroUnder: "By the Rowing Canal, beside the river in Plovdiv.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Photograph of the complex",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The complex, the garden and the courtyard.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "the photographs are their own, from ostrova-plovdiv.com",
  },
} as const;
