// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/rhodope-house",
  metaTitle: "Родопска къща | Сватби и тържества в Асеновград",
  metaDescription: "Традиционен ресторант и хотел на бул. „България“ 128 в Асеновград. Организация на сватби и годежи, безплатен паркинг. Резервации на 088 736 2666.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Родопска къща",
  nameEn: "Rodopska Kashta",
  town: "Асеновград",
  since: "",
  phone: "088 736 2666",
  phoneHref: "tel:+359887362666",
  email: "",
  logoSrc: "",
  logoInNav: false,
  address: "бул. „България“ 128, Асеновград",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "https://www.facebook.com/rodopskakushta",
} as const;

export const palette = {
  note: "Родопска къща: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  tableBand: "",
  heroTone: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Ресторантът",
        note: "традиционна кухня",
        value: "капацитет по запитване",
      },
      {
        space: "Стаите",
        note: "за гостите, които остават",
        value: "на място",
      },
      {
        space: "Паркингът",
        note: "за гостите",
        value: "безплатен",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите в ресторанта",
        when: "начало",
      },
      {
        what: "Вечеря с традиционна кухня",
        when: "вечерта",
      },
      {
        what: "Гостите, които остават, спят на място",
        when: "до сутринта",
      },
    ],
    packagesNote: "Родопска къща не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The restaurant",
        note: "traditional kitchen",
        value: "capacity on request",
      },
      {
        space: "The rooms",
        note: "for guests who stay",
        value: "on site",
      },
      {
        space: "The parking",
        note: "for guests",
        value: "free",
      },
    ],
    timetable: [
      {
        what: "Guests are received in the restaurant",
        when: "start",
      },
      {
        what: "Dinner from a traditional kitchen",
        when: "evening",
      },
      {
        what: "Guests who stay sleep on site",
        when: "till morning",
      },
    ],
    packagesNote: "Rodopska Kashta publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Традиционна къща за сватби и годежи.",
    heroUnder: "Ресторант и хотел на бул. „България“ 128 в Асеновград, с безплатен паркинг.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Ресторантът и стаите за гостите.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "A traditional house for weddings and engagements.",
    heroUnder: "A restaurant and hotel at 128 Bulgaria Blvd in Asenovgrad, with free parking.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The restaurant and the guest rooms.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
