// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/number-five",
  metaTitle: "Парти зала Number Five | Тържества в Пловдив",
  metaDescription: "Обзаведена парти зала в жк Тракия, Пловдив, с бар, аудио система, караоке и парти осветление. За рождени дни, годишнини и сватби.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Парти зала Number Five",
  nameEn: "Number Five Party Hall",
  town: "Пловдив",
  since: "",
  phone: "0888 66 43 43",
  phoneHref: "tel:+359888664343",
  email: "info@numberfivebg.com",
  logoSrc: "",
  logoInNav: false,
  address: "ул. „Инж. Асен Йорданов“ 29, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Парти зала Number Five: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "/atmosphere/hero-numberfive.webp",
  wallGarden: "/atmosphere/wall-lounge.webp",
  wallHall: "/atmosphere/wall-barat.webp",
  wallTerrace: "/atmosphere/wall-bilyard.webp",
  tableBand: "/atmosphere/band-lounge.webp",
  heroTone: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Залата",
        note: "наема се цялата, частно",
        value: "брой места по запитване",
      },
      {
        space: "Барът",
        note: "витрини, чаши, съдомиялна",
        value: "на място",
      },
      {
        space: "Билярд и караоке",
        note: "включени в залата",
        value: "на място",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите в залата",
        when: "начало",
      },
      {
        what: "Вечеря, с бар на място",
        when: "вечерта",
      },
      {
        what: "Караоке и танци под парти осветлението",
        when: "до късно",
      },
    ],
    packagesNote: "Парти зала Number Five не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The hall",
        note: "rented whole, privately",
        value: "capacity on request",
      },
      {
        space: "The bar",
        note: "fridges, glassware, dishwasher",
        value: "on site",
      },
      {
        space: "Billiards and karaoke",
        note: "included with the hall",
        value: "on site",
      },
    ],
    timetable: [
      {
        what: "Guests are received in the hall",
        when: "start",
      },
      {
        what: "Dinner, with the bar on site",
        when: "evening",
      },
      {
        what: "Karaoke and dancing under the party lighting",
        when: "till late",
      },
    ],
    packagesNote: "Number Five Party Hall publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Зала, в която всичко вече е на място.",
    heroUnder: "Бар, аудио система, караоке и парти осветление в жк Тракия, Пловдив.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Залата и барът.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "снимките са техни собствени, от numberfivebg.com",
  },
  en: {
    heroTitle: "A hall where everything is already in place.",
    heroUnder: "A bar, an audio system, karaoke and party lighting in Trakia, Plovdiv.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The hall and the bar.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "the photographs are their own, from numberfivebg.com",
  },
} as const;
