// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/pavazh",
  metaTitle: "Паваж | Гастропъб в Капана, Пловдив",
  metaDescription: "Гастропъб на ул. „Златарска“ 7 в Капана, Пловдив, с места на открито. Резервации на 087 811 1876.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Паваж",
  nameEn: "Pavazh",
  town: "Пловдив",
  since: "",
  phone: "087 811 1876",
  phoneHref: "tel:+359878111876",
  email: "",
  logoSrc: "",
  address: "ул. „Златарска“ 7, Капана, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "https://www.facebook.com/pavaj.plovdiv/",
} as const;

export const palette = {
  note: "Паваж: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Заведението",
        note: "ул. „Златарска“ 7, Капана",
        value: "капацитет по запитване",
      },
      {
        space: "Местата на открито",
        note: "по паважа",
        value: "на място",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите",
        when: "начало",
      },
      {
        what: "Вечеря вътре или на паважа",
        when: "вечерта",
      },
      {
        what: "Вечерта продължава",
        when: "до късно",
      },
    ],
    packagesNote: "Паваж не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The place",
        note: "7 Zlatarska St, Kapana",
        value: "capacity on request",
      },
      {
        space: "The outdoor seating",
        note: "on the cobbles",
        value: "on site",
      },
    ],
    timetable: [
      {
        what: "Guests are received",
        when: "start",
      },
      {
        what: "Dinner inside or on the cobbles",
        when: "evening",
      },
      {
        what: "The evening goes on",
        when: "till late",
      },
    ],
    packagesNote: "Pavazh publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Всички павета водят към Капана.",
    heroUnder: "Гастропъб на ул. „Златарска“ 7, с места за гости на открито.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Заведението и местата на открито.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "Every cobble leads to Kapana.",
    heroUnder: "A gastropub at 7 Zlatarska Street, with outdoor seating for guests.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The place and its outdoor seating.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
