// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/pavazh",
  metaTitle: "Паваж | Гастропъб в Капана, Пловдив",
  metaDescription: "Гастропъб на ул. „Златарска“ 7 в Капана, Пловдив, с места на открито. Резервации на 087 811 1876.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Паваж",
  nameEn: "Pavazh",
  town: "Пловдив",
  since: "",
  phone: "087 811 1876",
  phoneHref: "tel:+359878111876",
  email: "",
  logoSrc: "/brand/pavazh-mark.webp",
  logoInNav: true,
  address: "ул. „Златарска“ 7, Капана, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "https://www.facebook.com/pavaj.plovdiv/",
} as const;

export const palette = {
  note: "Паваж: черна стенсил марка + синият час и амбърът на лампичките в Капана (взети от собствените им снимки във Facebook, 2026-08-27).",
} as const;

export const images = {
  heroFilm: "/atmosphere/hero-kapana.webp",
  wallGarden: "/atmosphere/wall-bar.webp",
  wallHall: "/atmosphere/wall-vecher.webp",
  wallTerrace: "/atmosphere/wall-paveta.webp",
  tableBand: "/atmosphere/band-vecheria.webp",
  heroTone: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Заведението",
        note: "ул. „Златарска“ 7, Капана",
        value: "капацитет по запитване",
      },
      {
        space: "Местата на открито",
        note: "по паважа",
        value: "на място",
      },
      {
        space: "Кухнята",
        note: "работи от обяд",
        value: "до единайсет вечерта",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите",
        when: "начало",
      },
      {
        what: "Вечеря вътре или на паважа",
        when: "вечерта",
      },
      {
        what: "Вечерта продължава",
        when: "до късно",
      },
    ],
    packagesNote: "Паваж не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The place",
        note: "7 Zlatarska St, Kapana",
        value: "capacity on request",
      },
      {
        space: "The outdoor seating",
        note: "on the cobbles",
        value: "on site",
      },
      {
        space: "The kitchen",
        note: "works from noon",
        value: "till eleven at night",
      },
    ],
    timetable: [
      {
        what: "Guests are received",
        when: "start",
      },
      {
        what: "Dinner inside or on the cobbles",
        when: "evening",
      },
      {
        what: "The evening goes on",
        when: "till late",
      },
    ],
    packagesNote: "Pavazh publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Всички павета водят към Капана.",
    heroUnder: "Гастропъб на ул. „Златарска“ 7, с места за гости на открито.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Реална снимка от Капана",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Заведението и местата на открито.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "реални снимки на заведението",
    heroCaptionReal: "Реална снимка от Капана",
  },
  en: {
    heroTitle: "Every cobble leads to Kapana.",
    heroUnder: "A gastropub at 7 Zlatarska Street, with outdoor seating for guests.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "A real photograph from Kapana",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The place and its outdoor seating.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "real photographs of the place",
    heroCaptionReal: "A real photograph from Kapana",
  },
} as const;
