// Generated by /webbuild reskin.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/malak-bunardzhik",
  metaTitle: "Малкия Бунарджик | Сватби в парк Бунарджик, Пловдив",
  metaDescription: "Зала и градина за по 150 гости под дърветата на парк „Бунарджик“, в сърцето на Пловдив.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Малкия Бунарджик",
  nameEn: "Malkia Bunardzhik",
  town: "Пловдив",
  since: "",
  phone: "0878 711 777",
  phoneHref: "tel:+359878711777",
  email: "",
  logoSrc: "",
  address: "парк „Бунарджик“, ул. Волга 1А, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Малкия Бунарджик: brand palette carried over from the 2026-07 vertical build (venue-true).",
} as const;

export const images = {
  heroFilm: "",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [{
      space: "Залата",
      note: "в сърцето на парка",
      value: "150 места",
    }, {
      space: "Градината",
      note: "под дърветата",
      value: "150 места",
    }, {
      space: "Работното време",
      note: "за тържества",
      value: "до 01:00 часа",
    }],
    timetable: [{
      what: "Посрещане в градината",
      when: "начало",
    }, {
      what: "Вечеря от кухнята на място",
      when: "вечерта",
    }, {
      what: "Танци под дърветата",
      when: "до 01:00",
    }],
    packagesNote: "Част от Ресторанти „Южен Полъх“, с кухня на място. Опишете тържеството си във формата.",
  },
  en: {
    capacityRows: [{
      space: "The hall",
      note: "in the heart of the park",
      value: "150 seats",
    }, {
      space: "The garden",
      note: "under the trees",
      value: "150 seats",
    }, {
      space: "Working hours",
      note: "for celebrations",
      value: "until 1:00 am",
    }],
    timetable: [{
      what: "Welcome in the garden",
      when: "start",
    }, {
      what: "Dinner from the on-site kitchen",
      when: "evening",
    }, {
      what: "Dancing under the trees",
      when: "until 1 am",
    }],
    packagesNote: "Part of the Yuzhen Polah restaurant group, with an on-site kitchen. Describe your celebration in the form.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Паркът е декорът на вашата вечер.",
    heroUnder: "Зала и градина за по 150 гости, под дърветата на парк „Бунарджик“.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Залата, градината и паркът.",
    duetTitle: "Вечерта минава под дърветата.",
    inviteLine: "Заповядайте на оглед. Паркът е на пет минути от центъра.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "The park is the decor of your evening.",
    heroUnder: "A hall and a garden for 150 guests each, under the trees of Bunardzhik Park.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "One evening, one place.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
