// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/chiirite",
  metaTitle: "Хотел „Чиирите“ | Сватбени тържества край Пловдив",
  metaDescription: "Хотел с мултифункционална зала и ресторант със 70 места на Околовръстния път на Пловдив. Сватбени тържества. Запитване на 032 202 600.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Хотел „Чиирите“",
  nameEn: "Hotel Chiirite",
  town: "Пловдив",
  since: "",
  phone: "032 202 600",
  phoneHref: "tel:+35932202600",
  email: "",
  logoSrc: "",
  address: "Околовръстен път, местност Чиирите 020B, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Хотел „Чиирите“: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Ресторантът",
        note: "работи от 7:30 до 23:00",
        value: "70 места",
      },
      {
        space: "Залата",
        note: "мултифункционална, с мултимедия",
        value: "капацитет по запитване",
      },
      {
        space: "Стаите",
        note: "за гостите, които остават",
        value: "на място",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите в залата",
        when: "начало",
      },
      {
        what: "Вечеря в ресторанта",
        when: "вечерта",
      },
      {
        what: "Гостите, които остават, спят на място",
        when: "до сутринта",
      },
    ],
    packagesNote: "Хотел „Чиирите“ не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The restaurant",
        note: "open 7:30 until 23:00",
        value: "70 seats",
      },
      {
        space: "The hall",
        note: "multifunctional, with multimedia",
        value: "capacity on request",
      },
      {
        space: "The rooms",
        note: "for guests who stay",
        value: "on site",
      },
    ],
    timetable: [
      {
        what: "Guests are received in the hall",
        when: "start",
      },
      {
        what: "Dinner in the restaurant",
        when: "evening",
      },
      {
        what: "Guests who stay sleep on site",
        when: "till morning",
      },
    ],
    packagesNote: "Hotel Chiirite publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Залата, ресторантът и стаите на едно място.",
    heroUnder: "На Околовръстния път на Пловдив, със седемдесет места в ресторанта.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Залата и ресторантът.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "The hall, the restaurant and the rooms in one place.",
    heroUnder: "On the Plovdiv ring road, with seventy seats in the restaurant.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The hall and the restaurant.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
