// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/panorama-sp",
  metaTitle: "Ресторант „Панорама“ | Тържества над Пловдив",
  metaDescription: "Панорамен ресторант на двайсет и втория етаж на бул. „България“ 97 в Пловдив. Запитване на 088 868 6817.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Ресторант „Панорама“",
  nameEn: "Panorama Restaurant",
  town: "Пловдив",
  since: "",
  phone: "088 868 6817",
  phoneHref: "tel:+359888686817",
  email: "",
  logoSrc: "",
  address: "бул. „България“ 97, ет. 22, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Ресторант „Панорама“: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Ресторантът",
        note: "двайсет и вторият етаж",
        value: "капацитет по запитване",
      },
      {
        space: "Изгледът",
        note: "над целия град",
        value: "панорамен",
      },
    ],
    timetable: [
      {
        what: "Изкачване и посрещане на гостите",
        when: "начало",
      },
      {
        what: "Вечеря покрай прозорците",
        when: "вечерта",
      },
      {
        what: "Градът светва под масата",
        when: "до късно",
      },
    ],
    packagesNote: "Ресторант „Панорама“ не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The restaurant",
        note: "the twenty-second floor",
        value: "capacity on request",
      },
      {
        space: "The view",
        note: "over the whole city",
        value: "panoramic",
      },
    ],
    timetable: [
      {
        what: "The climb and the welcome",
        when: "start",
      },
      {
        what: "Dinner along the windows",
        when: "evening",
      },
      {
        what: "The city lights up below",
        when: "till late",
      },
    ],
    packagesNote: "Panorama Restaurant publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Целият град е под масата.",
    heroUnder: "Панорамен ресторант на двайсет и втория етаж на бул. „България“ 97.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Ресторантът и изгледът.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "The whole city lies below the table.",
    heroUnder: "A panoramic restaurant on the twenty-second floor at 97 Bulgaria Boulevard.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The restaurant and the view.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
