// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/panorama-sp",
  metaTitle: "Ресторант „Панорама“ | Тържества над Пловдив",
  metaDescription: "Панорамен ресторант на двайсет и втория етаж на бул. „България“ 97 в Пловдив. Запитване на 088 868 6817.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Ресторант „Панорама“",
  nameEn: "Panorama Restaurant",
  town: "Пловдив",
  since: "",
  phone: "088 868 6817",
  phoneHref: "tel:+359888686817",
  email: "",
  logoSrc: "",
  logoInNav: false,
  address: "бул. „България“ 97, ет. 22, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Ресторант „Панорама“: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "/atmosphere/hero-panorama.webp",
  wallGarden: "/atmosphere/wall-izgled.webp",
  wallHall: "/atmosphere/wall-nosht.webp",
  wallTerrace: "/atmosphere/wall-masata.webp",
  tableBand: "/atmosphere/band-restorant.webp",
  heroTone: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Ресторант „Панорама“",
        note: "22-ри етаж, с лятна градина",
        value: "120 места",
      },
      {
        space: "Зала Пълдин",
        note: "най-голямата в комплекса",
        value: "до 300 театрално",
      },
      {
        space: "Зали Нева и Дружба",
        note: "за по-малки групи",
        value: "35 и 40 места",
      },
    ],
    timetable: [
      {
        what: "Изкачване и посрещане на гостите",
        when: "начало",
      },
      {
        what: "Вечеря покрай прозорците",
        when: "вечерта",
      },
      {
        what: "Градът светва под масата",
        when: "до късно",
      },
    ],
    packagesNote: "Ресторант „Панорама“ не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "Panorama Restaurant",
        note: "22nd floor, with a summer garden",
        value: "120 seats",
      },
      {
        space: "Puldin hall",
        note: "the largest in the complex",
        value: "up to 300 theatre-style",
      },
      {
        space: "Neva and Druzhba halls",
        note: "for smaller groups",
        value: "35 and 40 seats",
      },
    ],
    timetable: [
      {
        what: "The climb and the welcome",
        when: "start",
      },
      {
        what: "Dinner along the windows",
        when: "evening",
      },
      {
        what: "The city lights up below",
        when: "till late",
      },
    ],
    packagesNote: "Panorama Restaurant publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Целият град е под масата.",
    heroUnder: "Панорамен ресторант на двайсет и втория етаж на бул. „България“ 97.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Снимка на ресторанта",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Ресторантът и изгледът.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "снимките са техни собствени, от sphotel.net",
  },
  en: {
    heroTitle: "The whole city lies below the table.",
    heroUnder: "A panoramic restaurant on the twenty-second floor at 97 Bulgaria Boulevard.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Photograph of the restaurant",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The restaurant and the view.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "the photographs are their own, from sphotel.net",
  },
} as const;
