// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/rusalka",
  metaTitle: "Сватбен ресторант „Русалка“ | Пловдив",
  metaDescription: "Сватбен ресторант на бул. „Дунав“ 194 в Пловдив. Запитване за дата на 089 555 8949.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Сватбен ресторант „Русалка“",
  nameEn: "Rusalka Wedding Restaurant",
  town: "Пловдив",
  since: "",
  phone: "089 555 8949",
  phoneHref: "tel:+359895558949",
  email: "",
  logoSrc: "",
  address: "бул. „Дунав“ 194, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Сватбен ресторант „Русалка“: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Ресторантът",
        note: "бул. „Дунав“ 194",
        value: "капацитет по запитване",
      },
      {
        space: "Поводът",
        note: "сватбени тържества",
        value: "единствен",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите в ресторанта",
        when: "начало",
      },
      {
        what: "Вечеря на място",
        when: "вечерта",
      },
      {
        what: "Танците продължават",
        when: "до късно",
      },
    ],
    packagesNote: "Сватбен ресторант „Русалка“ не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The restaurant",
        note: "194 Dunav Blvd",
        value: "capacity on request",
      },
      {
        space: "The occasion",
        note: "wedding celebrations",
        value: "the only one",
      },
    ],
    timetable: [
      {
        what: "Guests are received in the restaurant",
        when: "start",
      },
      {
        what: "Dinner on site",
        when: "evening",
      },
      {
        what: "The dancing continues",
        when: "till late",
      },
    ],
    packagesNote: "Rusalka Wedding Restaurant publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Ресторант, който носи сватбата в името си.",
    heroUnder: "На бул. „Дунав“ 194 в Пловдив.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Ресторантът на бул. „Дунав“.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "A restaurant with the wedding in its name.",
    heroUnder: "At 194 Dunav Boulevard in Plovdiv.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The restaurant on Dunav Boulevard.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
