// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/ramido",
  metaTitle: "Рамидо | Зала за сватби в центъра на Пловдив",
  metaDescription: "Зала за събития на бул. „Руски“ 15 в центъра на Пловдив. Запитване за дата на 088 509 0993.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Рамидо",
  nameEn: "Ramido",
  town: "Пловдив",
  since: "",
  phone: "088 509 0993",
  phoneHref: "tel:+359885090993",
  email: "",
  logoSrc: "",
  logoInNav: false,
  address: "бул. „Руски“ 15, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Рамидо: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  tableBand: "",
  heroTone: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Залата",
        note: "бул. „Руски“ 15",
        value: "капацитет по запитване",
      },
      {
        space: "Локацията",
        note: "центърът на Пловдив",
        value: "пеша",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите в залата",
        when: "начало",
      },
      {
        what: "Вечеря в центъра на града",
        when: "вечерта",
      },
      {
        what: "Танците продължават",
        when: "до късно",
      },
    ],
    packagesNote: "Рамидо не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The hall",
        note: "15 Ruski Blvd",
        value: "capacity on request",
      },
      {
        space: "The location",
        note: "central Plovdiv",
        value: "on foot",
      },
    ],
    timetable: [
      {
        what: "Guests are received in the hall",
        when: "start",
      },
      {
        what: "Dinner in the city centre",
        when: "evening",
      },
      {
        what: "The dancing continues",
        when: "till late",
      },
    ],
    packagesNote: "Ramido publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Зала в центъра на града.",
    heroUnder: "На бул. „Руски“ 15, на крачки от всичко в Пловдив.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Залата на бул. „Руски“.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "A hall in the centre of the city.",
    heroUnder: "At 15 Ruski Boulevard, a short walk from everything in Plovdiv.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The hall on Ruski Boulevard.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
