// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/garden-romantic",
  metaTitle: "Ресторант „Романтик“ | Тържества в Пловдив",
  metaDescription: "Ресторант с градина на ул. „Вълко Шопов“ 4 в жк Тракия, Пловдив. Места на открито. Запитване на 087 700 7375.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Ресторант „Романтик“",
  nameEn: "Restaurant Romantic",
  town: "Пловдив",
  since: "",
  phone: "087 700 7375",
  phoneHref: "tel:+359877007375",
  email: "",
  logoSrc: "",
  logoInNav: false,
  address: "ул. „Вълко Шопов“ 4, жк Тракия, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "https://www.facebook.com/profile.php?id=100063630518349",
} as const;

export const palette = {
  note: "Ресторант „Романтик“: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  tableBand: "",
  heroTone: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Градината",
        note: "места за гости на открито",
        value: "капацитет по запитване",
      },
      {
        space: "Ресторантът",
        note: "жк Тракия",
        value: "на място",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите в градината",
        when: "начало",
      },
      {
        what: "Вечеря на открито или вътре",
        when: "вечерта",
      },
      {
        what: "Вечерта продължава до полунощ",
        when: "до късно",
      },
    ],
    packagesNote: "Ресторант „Романтик“ не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The garden",
        note: "outdoor seating for guests",
        value: "capacity on request",
      },
      {
        space: "The restaurant",
        note: "Trakia district",
        value: "on site",
      },
    ],
    timetable: [
      {
        what: "Guests are received in the garden",
        when: "start",
      },
      {
        what: "Dinner outdoors or inside",
        when: "evening",
      },
      {
        what: "The evening runs until midnight",
        when: "till late",
      },
    ],
    packagesNote: "Restaurant Romantic publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Атмосфера, която превръща всеки повод в празник.",
    heroUnder: "Ресторант с градина на ул. „Вълко Шопов“ 4 в жк Тракия.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Градината и местата на открито.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "An atmosphere that turns any occasion into a celebration.",
    heroUnder: "A restaurant with a garden at 4 Valko Shopov Street in Trakia.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The garden and the outdoor seating.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
