// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/fiesta-paga",
  metaTitle: "Сватбена зала „Фиеста“ | Пловдив",
  metaDescription: "Сватбена зала на бул. „Васил Априлов“ 152А в Пловдив, отворена всеки ден от 9 до 23 часа.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Сватбена зала „Фиеста“",
  nameEn: "Fiesta Wedding Hall",
  town: "Пловдив",
  since: "",
  phone: "",
  phoneHref: "",
  email: "",
  logoSrc: "",
  logoInNav: false,
  address: "бул. „Васил Априлов“ 152А, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Сватбена зала „Фиеста“: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "/atmosphere/hero-fiesta-paga.webp",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  tableBand: "",
  heroTone: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Залата",
        note: "бул. „Васил Априлов“ 152А",
        value: "капацитет по запитване",
      },
      {
        space: "Работно време",
        note: "всеки ден",
        value: "9 до 23 часа",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите в залата",
        when: "начало",
      },
      {
        what: "Вечеря в залата",
        when: "вечерта",
      },
      {
        what: "Танците продължават до 23 часа",
        when: "до късно",
      },
    ],
    packagesNote: "Сватбена зала „Фиеста“ не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The hall",
        note: "152A Vasil Aprilov Blvd",
        value: "capacity on request",
      },
      {
        space: "Opening hours",
        note: "every day",
        value: "9 until 23",
      },
    ],
    timetable: [
      {
        what: "Guests are received in the hall",
        when: "start",
      },
      {
        what: "Dinner in the hall",
        when: "evening",
      },
      {
        what: "The dancing continues until 23",
        when: "till late",
      },
    ],
    packagesNote: "Fiesta Wedding Hall publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Сватбена зала, отворена всеки ден.",
    heroUnder: "На бул. „Васил Априлов“ 152А в Пловдив, от девет сутринта до единайсет вечерта.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Снимка от страницата им във Facebook",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Залата на бул. „Васил Априлов“.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "заглавната снимка е тяхна, от Facebook; вътрешните визуализации предстоят",
  },
  en: {
    heroTitle: "A wedding hall, open every day.",
    heroUnder: "At 152A Vasil Aprilov Boulevard in Plovdiv, from nine in the morning until eleven at night.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Photograph from their Facebook page",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The hall on Vasil Aprilov Boulevard.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "the header photograph is theirs, from Facebook; interior visuals to come",
  },
} as const;
