// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/the-chicken",
  metaTitle: "Ресторант „Пилето“ | Тържества в Пловдив",
  metaDescription: "Ресторант на бул. „България“ 178 в Пловдив, с места на открито. Резервации на 032 961 061.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Ресторант „Пилето“",
  nameEn: "Restaurant Pileto",
  town: "Пловдив",
  since: "",
  phone: "032 961 061",
  phoneHref: "tel:+35932961061",
  email: "",
  logoSrc: "",
  logoInNav: false,
  address: "бул. „България“ 178, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "https://www.facebook.com/restaurantrantpileto",
} as const;

export const palette = {
  note: "Ресторант „Пилето“: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "/atmosphere/hero-maps.webp",
  wallGarden: "/atmosphere/wall-garden.webp",
  wallHall: "",
  wallTerrace: "",
  tableBand: "",
  heroTone: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Ресторантът",
        note: "бул. „България“ 178",
        value: "капацитет по запитване",
      },
      {
        space: "Местата на открито",
        note: "пред заведението",
        value: "на място",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите",
        when: "начало",
      },
      {
        what: "Вечеря вътре или навън",
        when: "вечерта",
      },
      {
        what: "Вечерта продължава",
        when: "до късно",
      },
    ],
    packagesNote: "Ресторант „Пилето“ не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The restaurant",
        note: "178 Bulgaria Blvd",
        value: "capacity on request",
      },
      {
        space: "The outdoor seating",
        note: "in front",
        value: "on site",
      },
    ],
    timetable: [
      {
        what: "Guests are received",
        when: "start",
      },
      {
        what: "Dinner inside or out",
        when: "evening",
      },
      {
        what: "The evening goes on",
        when: "till late",
      },
    ],
    packagesNote: "Restaurant Pileto publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Малките неща имат най-голямо значение.",
    heroUnder: "Ресторант на бул. „България“ 178, с места за гости на открито.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Ресторантът и местата на открито.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "The small things always matter most.",
    heroUnder: "A restaurant at 178 Bulgaria Boulevard, with outdoor seating for guests.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The restaurant and its outdoor seating.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
