// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/casa-de-cuba",
  metaTitle: "Casa de Cuba | Поводи в Пловдив",
  metaDescription: "Заведение на бул. „Васил Априлов“ 118 в Пловдив, с 4.7 от отзивите в Google. Запитване на 088 500 8490.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Casa de Cuba",
  nameEn: "Casa de Cuba",
  town: "Пловдив",
  since: "",
  phone: "088 500 8490",
  phoneHref: "tel:+359885008490",
  email: "",
  logoSrc: "",
  logoInNav: false,
  address: "бул. „Васил Априлов“ 118, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Casa de Cuba: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  tableBand: "",
  heroTone: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Заведението",
        note: "бул. „Васил Априлов“ 118",
        value: "капацитет по запитване",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите",
        when: "начало",
      },
      {
        what: "Вечерята",
        when: "вечерта",
      },
      {
        what: "Вечерта продължава",
        when: "до късно",
      },
    ],
    packagesNote: "Casa de Cuba не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The place",
        note: "118 Vasil Aprilov Blvd",
        value: "capacity on request",
      },
    ],
    timetable: [
      {
        what: "Guests are received",
        when: "start",
      },
      {
        what: "Dinner",
        when: "evening",
      },
      {
        what: "The evening goes on",
        when: "till late",
      },
    ],
    packagesNote: "Casa de Cuba publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Вечерта има свое място.",
    heroUnder: "На бул. „Васил Априлов“ 118, на крачки от центъра на Пловдив.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Заведението на бул. „Васил Априлов“.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "The evening has a place of its own.",
    heroUnder: "At 118 Vasil Aprilov Boulevard, a short walk from the centre of Plovdiv.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The place on Vasil Aprilov Boulevard.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
