// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/garden-weddings",
  metaTitle: "Garden Weddings | Сватби в градина край Пловдив",
  metaDescription: "Място за сватбени тържества в парка на село Марково, в полите на Родопите, на кратко разстояние от Пловдив.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Garden Weddings",
  nameEn: "Garden Weddings",
  town: "Марково",
  since: "",
  phone: "089 996 5338",
  phoneHref: "tel:+359899965338",
  email: "",
  logoSrc: "",
  logoInNav: false,
  address: "Парк, с. Марково, община Родопи",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Garden Weddings: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  tableBand: "",
  heroTone: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Градината",
        note: "мястото на тържеството",
        value: "капацитет по запитване",
      },
      {
        space: "Паркът наоколо",
        note: "село Марково",
        value: "на място",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите в градината",
        when: "начало",
      },
      {
        what: "Вечеря на открито",
        when: "вечерта",
      },
      {
        what: "Танците продължават навън",
        when: "до късно",
      },
    ],
    packagesNote: "Garden Weddings не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The garden",
        note: "where the celebration is held",
        value: "capacity on request",
      },
      {
        space: "The park around it",
        note: "Markovo",
        value: "on site",
      },
    ],
    timetable: [
      {
        what: "Guests are received in the garden",
        when: "start",
      },
      {
        what: "Dinner in the open air",
        when: "evening",
      },
      {
        what: "The dancing continues outside",
        when: "till late",
      },
    ],
    packagesNote: "Garden Weddings publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Сватба в градина, извън града.",
    heroUnder: "В парка на село Марково, в полите на Родопите, на кратко разстояние от Пловдив.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Градината и паркът наоколо.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "A wedding in a garden, outside the city.",
    heroUnder: "In the park at Markovo, at the foot of the Rhodopes, a short drive from Plovdiv.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The garden and the park around it.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
