// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/atlantik",
  metaTitle: "Ресторант-градина „Атлантик“ | Сватби в Първенец",
  metaDescription: "Ресторант с градина в село Първенец край Пловдив. Запитване за дата на 088 772 1412.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Ресторант-градина „Атлантик“",
  nameEn: "Atlantik Garden Restaurant",
  town: "Първенец",
  since: "",
  phone: "088 772 1412",
  phoneHref: "tel:+359887721412",
  email: "",
  logoSrc: "",
  address: "ул. „Съединение“ 43, с. Първенец",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Ресторант-градина „Атлантик“: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Градината",
        note: "мястото на тържеството",
        value: "капацитет по запитване",
      },
      {
        space: "Ресторантът",
        note: "с. Първенец",
        value: "на място",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите в градината",
        when: "начало",
      },
      {
        what: "Вечеря на открито",
        when: "вечерта",
      },
      {
        what: "Танците продължават",
        when: "до късно",
      },
    ],
    packagesNote: "Ресторант-градина „Атлантик“ не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The garden",
        note: "where the celebration is held",
        value: "capacity on request",
      },
      {
        space: "The restaurant",
        note: "Parvenets",
        value: "on site",
      },
    ],
    timetable: [
      {
        what: "Guests are received in the garden",
        when: "start",
      },
      {
        what: "Dinner in the open air",
        when: "evening",
      },
      {
        what: "The dancing continues",
        when: "till late",
      },
    ],
    packagesNote: "Atlantik Garden Restaurant publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Ресторант с градина, извън града.",
    heroUnder: "В село Първенец, на кратко разстояние от Пловдив.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Градината на Атлантик.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "A restaurant with a garden, outside the city.",
    heroUnder: "In the village of Parvenets, a short drive from Plovdiv.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The garden at Atlantik.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
