// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/citizens-club",
  metaTitle: "Citizens Club | Ресторант в центъра на Пловдив",
  metaDescription: "Ресторант на ул. „Стоян Чалъков“ 1 в центъра на Пловдив. Запитване за повод на 087 862 4139.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Citizens Club",
  nameEn: "Citizens Club",
  town: "Пловдив",
  since: "",
  phone: "087 862 4139",
  phoneHref: "tel:+359878624139",
  email: "",
  logoSrc: "",
  logoInNav: false,
  address: "ул. „Стоян Чалъков“ 1, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Citizens Club: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "/atmosphere/hero-maps.webp",
  wallGarden: "/atmosphere/wall-garden.webp",
  wallHall: "",
  wallTerrace: "",
  tableBand: "",
  heroTone: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Ресторантът",
        note: "ул. „Стоян Чалъков“ 1",
        value: "капацитет по запитване",
      },
      {
        space: "Локацията",
        note: "центърът на Пловдив",
        value: "пеша",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите",
        when: "начало",
      },
      {
        what: "Вечеря в центъра",
        when: "вечерта",
      },
      {
        what: "Вечерта продължава",
        when: "до късно",
      },
    ],
    packagesNote: "Citizens Club не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The restaurant",
        note: "1 Stoyan Chalakov St",
        value: "capacity on request",
      },
      {
        space: "The location",
        note: "central Plovdiv",
        value: "on foot",
      },
    ],
    timetable: [
      {
        what: "Guests are received",
        when: "start",
      },
      {
        what: "Dinner in the centre",
        when: "evening",
      },
      {
        what: "The evening goes on",
        when: "till late",
      },
    ],
    packagesNote: "Citizens Club publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Ресторант в самия център.",
    heroUnder: "На ул. „Стоян Чалъков“ 1, на крачки от всичко в Пловдив.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Ресторантът в центъра.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "A restaurant in the centre itself.",
    heroUnder: "At 1 Stoyan Chalakov Street, a short walk from everything in Plovdiv.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The restaurant in the centre.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
