// Generated by /webbuild reskin.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/esterra-vini",
  metaTitle: "Esterra Vini | Сватби сред лозя и борова гора край Перущица",
  metaDescription: "Тържества на открито за 180 гости, четири къщи за настаняване и басейн сред лозята на Перущица.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Естера Вини",
  nameEn: "Esterra Vini",
  town: "гр. Перущица",
  since: "",
  phone: "0884 675 777",
  phoneHref: "tel:+359884675777",
  email: "reservations@anita.bg",
  logoSrc: "",
  address: "местност Пастуша, гр. Перущица",
  mapEmbedSrc: "",
  instagram: "https://www.instagram.com/esterravini/",
  facebook: "https://www.facebook.com/Esterra-Vini-Pool-137361743556852/",
} as const;

export const palette = {
  note: "Естера Вини: brand palette carried over from the 2026-07 vertical build (venue-true).",
} as const;

export const images = {
  heroFilm: "/photos/gal15-lg.webp",
  wallGarden: "/photos/ev12.webp",
  wallHall: "/photos/gal20.webp",
  wallTerrace: "/photos/gal16.webp",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [{
      space: "На открито",
      note: "сватбено тържество",
      value: "до 180 гости",
    }, {
      space: "Общото помещение",
      note: "зимен сезон",
      value: "30 гости",
    }, {
      space: "Къщите",
      note: "настаняване на място",
      value: "до 28 гости",
    }],
    timetable: [{
      what: "Коктейл за добре дошли",
      when: "начало",
    }, {
      what: "Брачна церемония, изнесен ритуал",
      when: "следобед",
    }, {
      what: "Празнична вечеря",
      when: "вечерта",
    }, {
      what: "Настаняване в къщите",
      when: "след празника",
    }],
    packagesNote: "Настаняване, коктейл, церемония и вечеря: имението поема целия ден. Опишете вашия във формата.",
  },
  en: {
    capacityRows: [{
      space: "Open air",
      note: "wedding celebration",
      value: "up to 180 guests",
    }, {
      space: "Winter room",
      note: "cold season",
      value: "30 guests",
    }, {
      space: "The houses",
      note: "on-site lodging",
      value: "up to 28 guests",
    }],
    timetable: [{
      what: "Welcome cocktail",
      when: "start",
    }, {
      what: "Outdoor wedding ceremony",
      when: "afternoon",
    }, {
      what: "Festive dinner",
      when: "evening",
    }, {
      what: "Overnight stay in the houses",
      when: "after the party",
    }],
    packagesNote: "Lodging, cocktail, ceremony and dinner: the estate hosts the whole day. Describe yours in the form.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Имението очаква вашето тържество.",
    heroUnder: "Тържества на открито за 180 гости, четири къщи за гостите и басейн сред лозята.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Лозята, басейнът и къщите.",
    duetTitle: "Вечерта остава в имението.",
    inviteLine: "Запитайте за дата. Идването до Пастуша си струва само по себе си.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "The estate awaits your celebration.",
    heroUnder: "Open-air celebrations for 180 guests, four guest houses and a pool among the vines.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "One evening, one place.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
