// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/restorant-fiesta",
  metaTitle: "Ресторант „Фиеста“ | Тържества в Пловдив",
  metaDescription: "Ресторант на ул. „Пере Тошев“ 45 в Пловдив, отворен от 8:30 до полунощ. Запитване на 087 820 1734.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Ресторант „Фиеста“",
  nameEn: "Restaurant Fiesta",
  town: "Пловдив",
  since: "",
  phone: "087 820 1734",
  phoneHref: "tel:+359878201734",
  email: "",
  logoSrc: "",
  logoInNav: false,
  address: "ул. „Пере Тошев“ 45, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Ресторант „Фиеста“: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  tableBand: "",
  heroTone: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Ресторантът",
        note: "ул. „Пере Тошев“ 45",
        value: "капацитет по запитване",
      },
      {
        space: "Работното време",
        note: "всеки ден",
        value: "8:30 до полунощ",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите",
        when: "начало",
      },
      {
        what: "Вечеря в ресторанта",
        when: "вечерта",
      },
      {
        what: "Вечерта продължава до полунощ",
        when: "до късно",
      },
    ],
    packagesNote: "Ресторант „Фиеста“ не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The restaurant",
        note: "45 Pere Toshev St",
        value: "capacity on request",
      },
      {
        space: "Opening hours",
        note: "every day",
        value: "8:30 until midnight",
      },
    ],
    timetable: [
      {
        what: "Guests are received",
        when: "start",
      },
      {
        what: "Dinner in the restaurant",
        when: "evening",
      },
      {
        what: "The evening runs until midnight",
        when: "till late",
      },
    ],
    packagesNote: "Restaurant Fiesta publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Ресторант, отворен от сутринта до полунощ.",
    heroUnder: "На ул. „Пере Тошев“ 45 в южната част на Пловдив.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Ресторантът на ул. „Пере Тошев“.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "A restaurant open from morning until midnight.",
    heroUnder: "At 45 Pere Toshev Street in the southern part of Plovdiv.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The restaurant on Pere Toshev Street.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
