// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/joana",
  metaTitle: "Ресторант „Джоана“ | Тържества в Пловдив",
  metaDescription: "Ресторант на бул. „Дунав“ и ул. „Победа“ в Кършияка, Пловдив. Резервации на 088 830 2428.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Ресторант „Джоана“",
  nameEn: "Restaurant Joana",
  town: "Пловдив",
  since: "",
  phone: "088 830 2428",
  phoneHref: "tel:+359888302428",
  email: "",
  logoSrc: "",
  logoInNav: false,
  address: "бул. „Дунав“ и ул. „Победа“, Кършияка, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Ресторант „Джоана“: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  tableBand: "",
  heroTone: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Салонът",
        note: "квартал Кършияка",
        value: "капацитет по запитване",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите",
        when: "начало",
      },
      {
        what: "Вечеря в салона",
        when: "вечерта",
      },
      {
        what: "Вечерта продължава",
        when: "до късно",
      },
    ],
    packagesNote: "Ресторант „Джоана“ не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The room",
        note: "Karshiyaka district",
        value: "capacity on request",
      },
    ],
    timetable: [
      {
        what: "Guests are received",
        when: "start",
      },
      {
        what: "Dinner in the room",
        when: "evening",
      },
      {
        what: "The evening goes on",
        when: "till late",
      },
    ],
    packagesNote: "Restaurant Joana publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Ресторант за поводите в Кършияка.",
    heroUnder: "На ъгъла на бул. „Дунав“ и ул. „Победа“.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Ресторантът и салонът.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "A restaurant for Karshiyaka's occasions.",
    heroUnder: "At the corner of Dunav Boulevard and Pobeda Street.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The restaurant and its room.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
