// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/paldin",
  metaTitle: "Ресторант „Пълдин“ | Тържества в Стария град, Пловдив",
  metaDescription: "Ресторант на ул. „Княз Церетелев“ 3 в Стария град на Пловдив. Резервации на 032 631 720.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Ресторант „Пълдин“",
  nameEn: "Paldin Restaurant",
  town: "Пловдив",
  since: "",
  phone: "032 631 720",
  phoneHref: "tel:+35932631720",
  email: "",
  logoSrc: "",
  logoInNav: false,
  address: "ул. „Княз Церетелев“ 3, Стария град, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Ресторант „Пълдин“: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  tableBand: "",
  heroTone: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Ресторантът",
        note: "Старият град, Пловдив",
        value: "капацитет по запитване",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите на хълма",
        when: "начало",
      },
      {
        what: "Вечеря в Стария град",
        when: "вечерта",
      },
      {
        what: "Вечерта продължава",
        when: "до късно",
      },
    ],
    packagesNote: "Ресторант „Пълдин“ не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The restaurant",
        note: "Old Town, Plovdiv",
        value: "capacity on request",
      },
    ],
    timetable: [
      {
        what: "Guests are received on the hill",
        when: "start",
      },
      {
        what: "Dinner in the Old Town",
        when: "evening",
      },
      {
        what: "The evening goes on",
        when: "till late",
      },
    ],
    packagesNote: "Paldin Restaurant publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Вечеря в Стария град.",
    heroUnder: "Ресторант на ул. „Княз Церетелев“ 3, сред възрожденските къщи.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Ресторантът на хълма.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "Dinner in the Old Town.",
    heroUnder: "A restaurant at 3 Knyaz Tseretelev Street, among the revival houses.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The restaurant on the hill.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
