// Generated by /webbuild reskin.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/zala-royal",
  metaTitle: "Сватбена зала Роял | Сватби до 440 гости в Асеновград",
  metaDescription: "Зала до 440 гости с просторен дансинг, градина за изнесен ритуал и собствена кухня в Асеновград.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Сватбена зала Роял",
  nameEn: "Zala Royal",
  town: "гр. Асеновград",
  since: "",
  phone: "0879 22 27 75",
  phoneHref: "tel:+359879222775",
  email: "",
  logoSrc: "/brand/royal-logo.png",
  address: "ул. Стоян Джансъзов 46, гр. Асеновград",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Сватбена зала Роял: brand palette carried over from the 2026-07 vertical build (venue-true).",
} as const;

export const images = {
  heroFilm: "/photos/zalata-lg.webp",
  wallGarden: "/photos/zalata-masi.webp",
  wallHall: "/photos/gradinata.webp",
  wallTerrace: "/photos/sgradata.webp",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [{
      space: "Залата",
      note: "гъвкаво пространство",
      value: "до 440 гости",
    }, {
      space: "Градината",
      note: "изнесен ритуал пред залата",
      value: "граждански брак",
    }, {
      space: "По-интимно",
      note: "същата зала, друга подредба",
      value: "до 100 гости",
    }],
    timetable: [{
      what: "Изнесен ритуал в градината",
      when: "начало",
    }, {
      what: "Вечеря от собствената кухня",
      when: "вечерта",
    }, {
      what: "Танци на просторния дансинг",
      when: "до късно",
    }],
    packagesNote: "Менюта, подготвяни на място, персонализирани декорации и професионално осветление. Опишете деня си във формата.",
  },
  en: {
    capacityRows: [{
      space: "The hall",
      note: "flexible space",
      value: "up to 440 guests",
    }, {
      space: "The garden",
      note: "ceremony in front of the hall",
      value: "civil weddings",
    }, {
      space: "More intimate",
      note: "same hall, different layout",
      value: "up to 100 guests",
    }],
    timetable: [{
      what: "Garden ceremony",
      when: "start",
    }, {
      what: "Dinner from the in-house kitchen",
      when: "evening",
    }, {
      what: "Dancing on the spacious floor",
      when: "till late",
    }],
    packagesNote: "Menus prepared on site, personalised decoration and professional lighting. Describe your day in the form.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Залата очаква до 440 гости.",
    heroUnder: "Просторен дансинг, градина за изнесен ритуал и собствена кухня в Асеновград.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Залата, градината и кухнята.",
    duetTitle: "Вечерта има място за всички.",
    inviteLine: "Заповядайте на оглед. Залата се показва най-добре празна и осветена.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "A hall for up to 440 guests.",
    heroUnder: "A spacious dance floor, a ceremony garden and an in-house kitchen in Asenovgrad.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "One evening, one place.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
