// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/hebros",
  metaTitle: "Хотел „Хеброс“ | Тържества в Стария град, Пловдив",
  metaDescription: "Хотел на ул. „Константин Стоилов“ 51 в Стария град на Пловдив, със стаи за гостите. Запитване на 088 822 0377.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Хотел и ресторант „Хеброс“",
  nameEn: "Hebros Hotel & Restaurant",
  town: "Пловдив",
  since: "",
  phone: "032 260 180",
  phoneHref: "tel:+35932260180",
  email: "reservation@oldlegends.bg",
  logoSrc: "/brand/hebros-mark.webp",
  logoInNav: true,
  address: "ул. „Константин Стоилов“ 51, Стария град, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Хотел и ресторант „Хеброс“: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "/atmosphere/hero-hebros.webp",
  wallGarden: "/atmosphere/wall-gradinata.webp",
  wallHall: "/atmosphere/wall-salonat.webp",
  wallTerrace: "/atmosphere/wall-dvorat.webp",
  tableBand: "/atmosphere/band-dvorat.webp",
  heroTone: "light",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Хотелът",
        note: "Старият град, Пловдив",
        value: "капацитет по запитване",
      },
      {
        space: "Стаите",
        note: "за гостите, които остават",
        value: "на място",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите на хълма",
        when: "начало",
      },
      {
        what: "Вечеря в Стария град",
        when: "вечерта",
      },
      {
        what: "Гостите, които остават, спят на място",
        when: "до сутринта",
      },
    ],
    packagesNote: "Хотел „Хеброс“ не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The hotel",
        note: "Old Town, Plovdiv",
        value: "capacity on request",
      },
      {
        space: "The rooms",
        note: "for guests who stay",
        value: "on site",
      },
    ],
    timetable: [
      {
        what: "Guests are received on the hill",
        when: "start",
      },
      {
        what: "Dinner in the Old Town",
        when: "evening",
      },
      {
        what: "Guests who stay sleep on site",
        when: "till morning",
      },
    ],
    packagesNote: "Hebros Hotel publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Тържеството и нощувката на един хълм.",
    heroUnder: "Хотел на ул. „Константин Стоилов“ 51, сред възрожденските къщи.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Снимка на хотела",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Хотелът в Стария град.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "снимките са техни собствени, от oldlegends.bg",
  },
  en: {
    heroTitle: "The celebration and the night, on one hill.",
    heroUnder: "A hotel at 51 Konstantin Stoilov Street, among the revival houses.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Photograph of the hotel",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The hotel in the Old Town.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "the photographs are their own, from oldlegends.bg",
  },
} as const;
