#!/bin/bash
# Build one gravura demo site from a venue facts JSON and stage it into the gallery repo.
# Usage: build_site.sh <slug>
set -euo pipefail
SLUG="$1"
REPO="$HOME/Desktop/web-agency/webbuild-plovdiv-wedding-venues"
TPL="$HOME/Desktop/web-agency/templates/wedding-venues/gravura"
WORK="$(mktemp -d)/$SLUG"
BASE="/webbuild-plovdiv-wedding-venues/sites/$SLUG"
URL="https://mitev22.github.io$BASE"

cp -R "$TPL" "$WORK"
python3 "$REPO/tools/gen_content.py"  "$REPO/tools/venues/$SLUG.json" "$WORK"
python3 "$REPO/tools/make_config.py"  "$REPO/tools/venues/$SLUG.json" "$WORK" "$URL"

( cd "$WORK" && SITE_BASE_PATH="$BASE" npx next build >/tmp/build-$SLUG.log 2>&1 ) \
  || { echo "BUILD FAILED — tail:"; tail -25 /tmp/build-$SLUG.log; exit 1; }

rm -rf "$REPO/sites/$SLUG" "$REPO/configs/$SLUG"
mkdir -p "$REPO/sites/$SLUG" "$REPO/configs/$SLUG"
cp -R "$WORK/out/." "$REPO/sites/$SLUG/"
cp "$WORK/lib/template.config.ts" "$WORK/lib/content.ts" "$WORK/lib/content-extra.ts" "$REPO/configs/$SLUG/"
sed -n '/:root/,/}/p' "$WORK/app/globals.css" > "$REPO/configs/$SLUG/globals-root.css"
cat > "$REPO/configs/$SLUG/BUILD.md" <<EOF
Template: gravura
Built: $(date +%Y-%m-%d)
SITE_BASE_PATH=$BASE
Content pack: generated by tools/gen_content.py from tools/venues/$SLUG.json
EOF
echo "BUILT $SLUG -> $URL"
