#!/usr/bin/env python3
"""Write lib/template.config.ts (the gravura tokens contract) from a venue JSON.

Usage: make_config.py <venue.json> <work_dir> <base_url>

Only the documented token surface is written. Palette values are NOT overridden
unless the venue JSON carries a `cssVars` block (a venue with no real brand
materials keeps the template's documented palette rather than an invented one).
"""
import json, re, sys
from pathlib import Path

vp, work, base = Path(sys.argv[1]), Path(sys.argv[2]), sys.argv[3]
V = json.loads(vp.read_text(encoding="utf-8"))
T = V.get("tokens", {})

def ts(o, ind=0):
    pad = "  " * ind
    if isinstance(o, dict):
        if not o: return "{}"
        return "{\n" + ",\n".join(f"{pad}  {k}: {ts(v, ind+1)}" for k, v in o.items()) + f",\n{pad}}}"
    if isinstance(o, list):
        if not o: return "[]"
        return "[\n" + ",\n".join(f"{pad}  {ts(v, ind+1)}" for v in o) + f",\n{pad}]"
    if isinstance(o, bool): return "true" if o else "false"
    if isinstance(o, (int, float)): return str(o)
    return json.dumps(o, ensure_ascii=False)

cfg = {
 "site": {"canonicalUrl": base.rstrip("/"), "metaTitle": V["meta"]["bg"]["title"],
          "metaDescription": V["meta"]["bg"]["desc"], "specDemo": True},
 "brand": {"nameBg": V["nameBg"], "nameEn": V.get("nameEn") or V["nameBg"],
           "town": V.get("town", "Пловдив"), "since": V.get("since", ""),
           "phone": (V.get("phone") or [""])[0],
           "phoneHref": ("tel:" + V["phoneE164"]) if V.get("phoneE164") else "",
           "email": V.get("email", ""), "logoSrc": V.get("logoSrc", ""),
           "logoInNav": bool(V.get("logoInNav")), "address": V["address"],
           "mapEmbedSrc": "", "instagram": V.get("instagram", ""),
           "facebook": V.get("facebook", "")},
 "palette": {"note": V.get("paletteNote",
             f"{V['nameBg']}: no brand materials published — template palette kept as documented.")},
 # Photograph slots. A venue that has supplied none keeps the empty strings and
 # the template renders its coded gradient stand-ins (see gravura/TEMPLATE.md).
 "images": {**{"heroFilm": "", "wallGarden": "", "wallHall": "", "wallTerrace": "",
               "tableBand": "", "heroTone": "", "ogImage": "/atmosphere/og-card.jpg"},
            **V.get("images", {})},
 "factsDict": {
   "bg": {"capacityRows": T.get("capacityRows", {}).get("bg", []),
          "timetable": T.get("timetable", {}).get("bg", []),
          "packagesNote": T.get("packagesNote", {}).get("bg", "")},
   "en": {"capacityRows": T.get("capacityRows", {}).get("en", []),
          "timetable": T.get("timetable", {}).get("en", []),
          "packagesNote": T.get("packagesNote", {}).get("en", "")}},
 "copyDict": {lang: T["copy"][lang] for lang in ("bg", "en")},
}

out = "// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)\n"
for name in ("site", "brand", "palette", "images", "factsDict", "copyDict"):
    out += f"\nexport const {name} = {ts(cfg[name])} as const;\n"
(work / "lib" / "template.config.ts").write_text(out, encoding="utf-8")

if V.get("cssVars"):
    css_path = work / "app" / "globals.css"
    css = css_path.read_text(encoding="utf-8")
    for var, val in V["cssVars"].items():
        css, n = re.subn(rf"(--{var}:\s*)[^;]+;", rf"\g<1>{val};", css, count=1)
        if not n: print(f"WARN: --{var} not found in :root")
    css_path.write_text(css, encoding="utf-8")
    print(f"globals.css: {len(V['cssVars'])} vars synced")
print("template.config.ts written:", V["nameBg"])
