#!/usr/bin/env python3
"""Gravura re-skin applicator — /webbuild mass production.

Usage: reskin.py <old_app_dir> <work_dir> <spec.json>

Applies ONLY the documented re-skin surface (gravura/TEMPLATE.md):
  lib/content.ts + lib/content-extra.ts   <- copied from the old venue app
  lib/template.config.ts                  <- generated from the spec
  app/globals.css :root values            <- palette from the spec
  public/{brand,photos,atmosphere}        <- copied from the old venue app
Components are never touched.
"""
import json, re, shutil, sys
from pathlib import Path

old, work, specp = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
spec = json.loads(specp.read_text())

# 1. Content pack
for f in ("content.ts", "content-extra.ts"):
    src = old / "lib" / f
    if src.exists():
        shutil.copy(src, work / "lib" / f)
        print(f"content: {f}")

# 2. Public assets (venue's real materials)
for d in ("brand", "photos", "atmosphere"):
    src = old / "public" / d
    if src.exists():
        dst = work / "public" / d
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst)
        print(f"assets: {d} ({sum(1 for _ in dst.iterdir())} files)")

# 2b. Normalize: empty packages array needs its type assertion (schema drift)
ct = work / "lib" / "content.ts"
src = ct.read_text()
src2 = re.sub(
    r"packages: \[\s*\](?! as)",
    "packages: [] as { name: string; menu: string; feesWaived: boolean; gift?: string }[]",
    src,
)
if src2 != src:
    ct.write_text(src2)
    print("normalized: empty packages assertion")

# 3. template.config.ts
def ts(obj, indent=0):
    pad = "  " * indent
    if isinstance(obj, dict):
        rows = ",\n".join(f"{pad}  {k}: {ts(v, indent + 1)}" for k, v in obj.items())
        return "{\n" + rows + f",\n{pad}}}"
    if isinstance(obj, list):
        rows = ", ".join(ts(v, indent) for v in obj)
        return f"[{rows}]"
    if isinstance(obj, bool):
        return "true" if obj else "false"
    return json.dumps(obj, ensure_ascii=False)

cfg = spec["config"]
out = "// Generated by /webbuild reskin.py — per-venue tokens (see gravura/TEMPLATE.md)\n"
for name in ("site", "brand", "palette", "images", "factsDict", "copyDict"):
    out += f"\nexport const {name} = {ts(cfg[name])} as const;\n"
(work / "lib" / "template.config.ts").write_text(out)
print("template.config.ts written")

# 4. globals.css :root palette sync
css_path = work / "app" / "globals.css"
css = css_path.read_text()
for var, val in spec["cssVars"].items():
    css, n = re.subn(rf"(--{var}:\s*)[^;]+;", rf"\g<1>{val};", css, count=1)
    if not n:
        print(f"WARN: --{var} not found in :root")
css_path.write_text(css)
print(f"globals.css: {len(spec['cssVars'])} vars synced")
print("RESKIN OK:", cfg["brand"]["nameBg"])
