// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/crystal-palace",
  metaTitle: "Crystal Palace | Сватбен салон в Пловдив",
  metaDescription: "Сватбен салон на ул. „Владая“ 17 в Пловдив, с места и на открито. Резервация на дата по телефон 088 857 7616.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Crystal Palace",
  nameEn: "Crystal Palace",
  town: "Пловдив",
  since: "",
  phone: "088 857 7616",
  phoneHref: "tel:+359888577616",
  email: "",
  logoSrc: "",
  address: "ул. „Владая“ 17, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "https://www.facebook.com/crystalpalaceplovdiv",
} as const;

export const palette = {
  note: "Crystal Palace: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Салонът",
        note: "използва се само за сватбени тържества",
        value: "капацитет по запитване",
      },
      {
        space: "Откритата част",
        note: "места за гости навън",
        value: "на място",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите в салона",
        when: "начало",
      },
      {
        what: "Вечеря на място, с места и на открито",
        when: "вечерта",
      },
      {
        what: "Танците продължават в салона",
        when: "до късно",
      },
    ],
    packagesNote: "Crystal Palace не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The salon",
        note: "used for wedding celebrations only",
        value: "capacity on request",
      },
      {
        space: "The outdoor area",
        note: "seating for guests outside",
        value: "on site",
      },
    ],
    timetable: [
      {
        what: "Guests are received in the salon",
        when: "start",
      },
      {
        what: "Dinner on site, with seating outdoors too",
        when: "evening",
      },
      {
        what: "The dancing continues in the salon",
        when: "till late",
      },
    ],
    packagesNote: "Crystal Palace publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Салон, който прави само сватби.",
    heroUnder: "На улица „Владая“ 17 в Пловдив, с места за гостите и на открито.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Салонът и откритата част.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "A salon that does weddings only.",
    heroUnder: "At 17 Vladaya Street in Plovdiv, with seating for guests outdoors as well.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The salon and the outdoor area.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
