// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/zala-kalinka",
  metaTitle: "Зала „Калинка“ | Сватбени тържества в Пловдив",
  metaDescription: "Зала за сватбени тържества в местност Беломорски, Пловдив. Организация на деня на място. Запитване за дата на 089 829 2880.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Зала „Калинка“",
  nameEn: "Kalinka Hall",
  town: "Пловдив",
  since: "",
  phone: "089 829 2880",
  phoneHref: "tel:+359898292880",
  email: "",
  logoSrc: "",
  logoInNav: false,
  address: "местност Беломорски 27А, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "",
} as const;

export const palette = {
  note: "Зала „Калинка“: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  tableBand: "",
  heroTone: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Залата",
        note: "мястото на тържеството",
        value: "капацитет по запитване",
      },
      {
        space: "Организацията",
        note: "поема се от домакините",
        value: "на място",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите в залата",
        when: "начало",
      },
      {
        what: "Вечеря в залата",
        when: "вечерта",
      },
      {
        what: "Танците продължават",
        when: "до късно",
      },
    ],
    packagesNote: "Зала „Калинка“ не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The hall",
        note: "where the celebration is held",
        value: "capacity on request",
      },
      {
        space: "The organising",
        note: "handled by the hosts",
        value: "on site",
      },
    ],
    timetable: [
      {
        what: "Guests are received in the hall",
        when: "start",
      },
      {
        what: "Dinner in the hall",
        when: "evening",
      },
      {
        what: "The dancing continues",
        when: "till late",
      },
    ],
    packagesNote: "Kalinka Hall publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Залата поема целия ден.",
    heroUnder: "В местност Беломорски в Пловдив, с организация на тържеството на място.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Залата и подготовката за деня.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "The hall takes on the whole day.",
    heroUnder: "In the Belomorski locality in Plovdiv, with the celebration organised on site.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The hall and the preparation for the day.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
