// Generated by /webbuild make_config.py — per-venue tokens (see gravura/TEMPLATE.md)

export const site = {
  canonicalUrl: "https://mitev22.github.io/webbuild-plovdiv-wedding-venues/sites/bohemys",
  metaTitle: "Bohemy’s Friends | Ирландски пъб и ресторант в Пловдив",
  metaDescription: "Ирландски пъб и ресторант на ул. „Недялка Шилева“ 11 в Пловдив. Запитване на 087 770 3104.",
  specDemo: true,
} as const;

export const brand = {
  nameBg: "Bohemy’s Friends",
  nameEn: "Bohemy’s Friends",
  town: "Пловдив",
  since: "",
  phone: "087 770 3104",
  phoneHref: "tel:+359877703104",
  email: "",
  logoSrc: "",
  address: "ул. „Недялка Шилева“ 11, Пловдив",
  mapEmbedSrc: "",
  instagram: "",
  facebook: "https://www.facebook.com/profile.php?id=100086960432432",
} as const;

export const palette = {
  note: "Bohemy’s Friends: no brand materials published — template palette kept as documented.",
} as const;

export const images = {
  heroFilm: "",
  wallGarden: "",
  wallHall: "",
  wallTerrace: "",
  ogImage: "/atmosphere/og-card.jpg",
} as const;

export const factsDict = {
  bg: {
    capacityRows: [
      {
        space: "Заведението",
        note: "ул. „Недялка Шилева“ 11",
        value: "капацитет по запитване",
      },
      {
        space: "Работното време",
        note: "по всяко време",
        value: "денонощно",
      },
    ],
    timetable: [
      {
        what: "Посрещане на гостите",
        when: "начало",
      },
      {
        what: "Вечеря в заведението",
        when: "вечерта",
      },
      {
        what: "Вечерта продължава",
        when: "до късно",
      },
    ],
    packagesNote: "Bohemy’s Friends не публикува куверт. Опишете деня си във формата и ще получите лична оферта.",
  },
  en: {
    capacityRows: [
      {
        space: "The place",
        note: "11 Nedyalka Shileva St",
        value: "capacity on request",
      },
      {
        space: "Opening hours",
        note: "at any hour",
        value: "around the clock",
      },
    ],
    timetable: [
      {
        what: "Guests are received",
        when: "start",
      },
      {
        what: "Dinner at the place",
        when: "evening",
      },
      {
        what: "The evening goes on",
        when: "till late",
      },
    ],
    packagesNote: "Bohemy’s Friends publishes no per-head price. Describe your day in the form for a personal offer.",
  },
} as const;

export const copyDict = {
  bg: {
    heroTitle: "Пъб, който остава отворен.",
    heroUnder: "Ирландски пъб и ресторант на ул. „Недялка Шилева“ 11.",
    heroCaption: "Час преди гостите.",
    heroCaptionNote: "Атмосферна визуализация",
    ctaEnquiry: "Запитване за дата",
    ctaVisit: "Заповядайте на оглед",
    wallTitle: "Заведението и масите.",
    duetTitle: "Вечерта минава на едно място.",
    inviteLine: "Заповядайте на оглед. Огледът трае час и не задължава с нищо.",
    enquiryTitle: "Запитване за дата",
    enquiryLead: "Опишете деня си: сезон, брой гости, ориентировъчен бюджет. Отговаряме лично на всяко запитване.",
    atmosphereNote: "атмосферни визуализации, предстои добавяне на снимки",
  },
  en: {
    heroTitle: "A pub that stays open.",
    heroUnder: "An Irish pub and restaurant at 11 Nedyalka Shileva Street.",
    heroCaption: "An hour before the guests.",
    heroCaptionNote: "Atmospheric visualisation",
    ctaEnquiry: "Enquire about a date",
    ctaVisit: "Come for a viewing",
    wallTitle: "The place and its tables.",
    duetTitle: "The evening, from start to finish.",
    inviteLine: "Come for a viewing. It commits you to nothing.",
    enquiryTitle: "Enquire about a date",
    enquiryLead: "Tell us about your day: season, guest count, approximate budget. Every enquiry gets a personal reply.",
    atmosphereNote: "atmospheric visualisations, venue photography to be added",
  },
} as const;
